# version: '3.8'

services:
  backend:
    # image: herdnet-backend
    build: ./backend
    ports:
      - "8000:8000"
    
    env_file:
      - .env.example
    
    volumes:
      - ./backend:/app
    networks:
      - herdnet-network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - herdnet-network
    restart: always

networks:
  herdnet-network:
    driver: bridge 