# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    
    env_file:
      - .env.example
    
    environment:
      - OPENAI_API_KEY= #${OPENAI_API_KEY}
      - TESSERACT_CMD=tesseract
    
    volumes:
      - ./backend:/app
    networks:
      - invoice-network
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - invoice-network
    restart: always

networks:
  invoice-network:
    driver: bridge 