[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000" 